### ISSUE TITLE
ServiceNotFoundException

### ISSUE THREAD

**Issue by sejalshah** [eddiejaoude/zf2-logger#18]
I am trying to install the module without "php composer.phar" but getting the error. 

Error : Uncaught exception 'Zend\ServiceManager\Exception\ServiceNotFoundException' with message 'Zend\ServiceManager\ServiceManager::get was unable to fetch or create an instance for EddieJaoude\Zf2Logger' in C:\Apache\htdocs\Zend\website\library\Zend\ServiceManager\ServiceManager.php:555

i copied all the files in vendor folder.

Waiting for reply.
Thanks 
Sejal Gada

**Comment by eddiejaoude** [comment]
Sorry, but the project only supports installation with **composer**. I have not tested it manually. I strongly suggest using composer. The only suggestion I can offer is check how you are loading in files from the vendors directory & make sure they are included.

**Comment by sejalshah** [comment]
Thank you for your prompt reply. I am now using php composer and its working fine. 
A suggestion to give provision to install this module manually in future.

**Comment by eddiejaoude** [comment]
> Thank you for your prompt reply

No problem.

> I am now using php composer and its working fine

Great :+1: 

> A suggestion to give provision to install this module manually in future.

Composer is the standard & recommended **Dependency Management**.  More information can be read here... http://www.phptherightway.com/#dependency_management
